name: Build Telegram Web

on:
  workflow_dispatch:
    inputs:
      api_id:
        description: 'API ID'
        required: true
        type: string
      api_hash:
        description: 'API Hash'
        required: true
        type: string
      domain:
        description: 'Domain'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          
      - name: Install dependencies
        run: npm ci --silent
        
      - name: Create config
        run: |
          echo "TELEGRAM_API_ID=${{ github.event.inputs.api_id }}" > .env
          echo "TELEGRAM_API_HASH=${{ github.event.inputs.api_hash }}" >> .env
          echo "BASE_URL=${{ github.event.inputs.domain }}" >> .env
          
      - name: Build
        run: npm run build:production
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          name: Release v1.0.0
          body: |
            Release notes here
          draft: false
          prerelease: false
          files: |
            dist/*
            !*.map
          generate_release_notes: true  # 这个支持！
